version: '3.8'

services:
  deepnorth-requests:
    build: .
    container_name: deepnorth-requests
    restart: unless-stopped
    ports:
      - "7650:3000"
    volumes:
      - sqlite_data:/app/database
    environment:
      - NODE_ENV=production
    
volumes:
  sqlite_data:
